# Generated by Django 5.0.1 on 2024-01-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.TextField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
